### ISSUE TITLE
Clonezilla Version Update

### ISSUE THREAD

**Issue by PrplHaz4** [OpenMediaVault-Plugin-Developers/openmediavault-kernel#1]
I ran into an issue where trying to boot one time to Clonezilla was failing with the error "unrecognized filesystem" and "try loading the kernel first" or similar.  I've yet to figure out what's causing it - but all other isos in the kernel plugin boot fine :-/.

I don't think this issue is related to the plugin, but realized this version of CZ is pretty old at this point (`2019-01-10 clonezilla-live-2.6.0-37-amd64.iso`).

Would you take a PR to update the CZ version or are there other non-obvious factors that would keep it from being a simple "update the version of CZ" pr?

**Comment by ryecoaaron** [comment]
This was done on purpose.  2.6.0-37 is the last version that you can tell clonezilla from a boot parameter to automatically start networking using dhcp.  Newer version require networking to be setup manually which ruins the use case I added it for - headless backup.

**Comment by PrplHaz4** [comment]
> This was done on purpose. 2.6.0-37 is the last version that you can tell clonezilla from a boot parameter to automatically start networking using dhcp. Newer version require networking to be setup manually which ruins the use case I added it for - headless backup.

I figured there was a reason. Thanks for the explanation!
