### ISSUE TITLE
Add option to remove/uninstall kernels

### ISSUE THREAD

**Issue by silopolis** [OpenMediaVault-Plugin-Developers/openmediavault-kernel#2]
That is again some great plugin.
Only thing I miss is being able to select and remove/uninstall kernels as they tend to accumulate over time.

Thanks again for your great work :pray:

**Comment by ryecoaaron** [comment]
The grub entry doesn't always make it easy to match to the kernel package.  I will look at this again but it seems risky for noobs who might remove the wrong kernel.

**Comment by silopolis** [comment]
Le jeu. 9 juin 2022 à 14:47, Aaron Murray ***@***.***> a
écrit :

> The grub entry doesn't always make it easy to match to the kernel package.
> I will look at this again but it seems risky for noobs who might remove the
> wrong kernel.
>

Indeed this should have all the belts and holders!
Not being able to remove the current kernel and the grub's default kernel
seem the minimum safety net

**Comment by PrplHaz4** [comment]
This is especially useful considering a lot of systems are booting off of relatively small devices (and in default config, the boot device is dedicated to the system not storage).

16GB boot is no longer enough to keep the system running without intervention for more than a few kernel updates.

Allowing cleanup from the UI would be one less reason a user needs to drop to a shell to fix things.

**Comment by ryecoaaron** [comment]
Can a few people post the output of:

`awk -F "'|\"" '$1 == "menuentry " { print $2 }' /boot/grub/grub.cfg | grep ^Debian | grep -v recovery | cut -d" " -f5`

**Comment by ryecoaaron** [comment]
Better yet...

```
kernels=$(awk -F "'|\"" '$1 == "menuentry " { print $2 }' /boot/grub/grub.cfg | grep ^Debian | grep -v recovery | cut -d" " -f5)
for i in ${kernels}; do echo ${i}; dpkg -l | grep ${i} | grep -E "pve-kernel|linux-image" | awk '{ print $2 }'; done
```

**Comment by PrplHaz4** [comment]
> Better yet...
> 
> ```
> kernels=$(awk -F "'|\"" '$1 == "menuentry " { print $2 }' /boot/grub/grub.cfg | grep ^Debian | grep -v recovery | cut -d" " -f5)
> for i in ${kernels}; do echo ${i}; dpkg -l | grep ${i} | grep -E "pve-kernel|linux-image" | awk '{ print $2 }'; done
> ```

Disclaimer - not likely a "clean" example - old system and recently recovered from a boot drive failure...

```
5.10.0-0.deb10.16-amd64
linux-image-5.10.0-0.deb10.16-amd64
5.10.0-0.bpo.12-amd64
linux-image-5.10.0-0.bpo.12-amd64
5.10.0-0.bpo.9-amd64
linux-image-5.10.0-0.bpo.9-amd64
```

**Comment by ryecoaaron** [comment]
@PrplHaz4 That is actually what I want since this plugin will have to work on many systems.  Thanks for the output.

**Comment by ryecoaaron** [comment]
6.4 is in the repo now and allows kernels to be removed.
