### ISSUE TITLE
Add Proxmox 6.2 kernel

### ISSUE THREAD

**Issue by igogold** [OpenMediaVault-Plugin-Developers/openmediavault-kernel#3]
The Proxmox team switched to use 6.2 kernel, version 6.1 will not get more updates. Source - [proxmox forum](https://forum.proxmox.com/threads/opt-in-linux-6-2-kernel-for-proxmox-ve-7-x-available.124189/). And [here](https://forum.proxmox.com/threads/opt-in-linux-6-2-kernel-for-proxmox-ve-7-x-available.124189/post-542916) they explain why 6.2 Linux kernel and not 6.1 LTS. In the [Proxmox 7.4 announcement](https://forum.proxmox.com/threads/proxmox-ve-7-4-released.124614/) also mentioned only 5.15 and 6.2 kernel versions.

Please add a new 6.2 kernel also.

**Comment by ryecoaaron** [comment]
Updated in 6.4.7 in repo now.
